GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJzYW5kaGlrYSIsImVtYWlsIjoiZW1haWxAZ21haWwuY29tIiwiaWF0IjoxNjk4MTI4OTc2LCJleHAiOjE2OTgxMjg5OTZ9.6lTEfKirfGtw-jmDEczHBUQP0Ol2RY7M5ashkVgbwEc

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "user3",
    "email": "email@gmail.com",
    "password": "123",
    "confPassword": "123"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "email@gmail.com",
    "password": "123"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout


# CATALOG -----------------------------------------------------------------

###
GET http://localhost:5000/catalog

###
GET http://localhost:5000/catalog/3

###
POST http://localhost:5000/catalog
Content-Type: application/json

{
    "nama_produk": "Nasi Uduk",
    "gambar": "nasiuduk.jpg",
    "harga": "11000",
    "publish": "1"
}

###
PATCH http://localhost:5000/catalog/1
Content-Type: application/json

{
    "harga": "15000"
}

###
DELETE http://localhost:5000/catalog/5
