GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJzYW5kaGlrYSIsImVtYWlsIjoiZW1haWxAZ21haWwuY29tIiwiaWF0IjoxNjk4MTI1ODk2LCJleHAiOjE2OTgxMjU5MTZ9.9O6Z5Ap40_fJpmlmQjcauLl5uv6AQr0oIL3IcPqDHSE

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "sandhika",
    "email": "email@gmail.com",
    "password": "123",
    "confPassword": "1234"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "email@gmail.com",
    "password": "123"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout

