GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJ1c2VyMyIsImVtYWlsIjoiZW1haWxAZ21haWwuY29tIiwiaWF0IjoxNzAwMDk5MDMzLCJleHAiOjE3MDAwOTkwNTN9.f9fZyHpP5S9CAgdLkNonRnHB3RjEfhH4oNzCmroI1RU

###
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJ1c2VyMyIsImVtYWlsIjoiZW1haWxAZ21haWwuY29tIiwiaWF0IjoxNzAwMTAwNDU4LCJleHAiOjE3MDAxMDA0Nzh9.XWvZJjzeTx_Dram2BmASAR_KZj9god8i0hByrk5Scm4

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "user3",
    "email": "email@gmail.com",
    "password": "123",
    "confPassword": "123"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "email@gmail.com",
    "password": "123"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout


# CATALOG -----------------------------------------------------------------

###
GET http://localhost:5000/catalog

###
GET http://localhost:5000/catalog/3

###
POST http://localhost:5000/catalog
Content-Type: application/json

{
    "nama_produk": "Nasi Uduk",
    "gambar": "nasiuduk.jpg",
    "harga": "11000",
    "publish": "1"
}

###
PATCH http://localhost:5000/catalog/1
Content-Type: application/json

{
    "harga": "15000"
}

###
DELETE http://localhost:5000/catalog/5
